version: '3.9'
services:
  web1:
    restart: on-failure
    build: ./web1
    expose: [5000]
  web2:
    restart: on-failure
    build: ./web2
    expose: [5000]
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web1
      - web2